###############################
#                             #
#          General            #
#                             #
###############################
# General settings for all anti-cheats
general:
  # Do you need to log received packets?
  isLogPacket: false
  # Types of Packets to Ignore
  ignorePacketType:
    - "PlayerUpdate"
    - "PlayerUpdateReliable"
    - "TimeSync"
    - "ZombieSimulation"
    - "Validate"
    - "SyncRadioData"
    - "PlayerListensChannel"
    - "ZombieSimulationReliable"
    - "ClientCommand"
    - "Vehicles"
    - "ChunkObjectState"
  # Do you need to additionally block the IP when blocking?
  isBanIpEnable: false
  # Do you need to additionally block SteamID (if a license) when blocking?
  isBanSteamIdEnable: false
  # Nicknames of players on whom the anti-cheat will not work (white list)
  whiteListUsername:
    - "admin"
  # Groups of user rights for which anti-cheat will not work (white list)
  whiteListGroup:
    - "admin"
    - "moderator"

###############################
#                             #
#          Discord            #
#                             #
###############################
# Display messages about punishments in the discord channel
discordAlert:
  # Notification status: true - enabled, false - disabled
  isEnable: false
  # Link to WebHook chat channel
  webHookURL: "..."
  # Nickname of the bot that will write notifications
  botUsername: "WatchDog"
  # Avatar of the bot that will write notifications
  botAvatarURL: "https://img.freepik.com/free-icon/dog_318-285321.jpg?size=626&ext=jpg"
  # Template of the message that will be displayed in the chat
  # Arguments:
  # <PLAYER_NAME> - player nickname
  # <ADMIN_NAME> - admin nickname
  # <DATE> - punishment date
  # <REASON> - reason for punishment
  messageTemplate: "```\nPlayer: <PLAYER_NAME>\nAdmin: <ADMIN_NAME>\nDate: <DATE>\nReason: <REASON>\n```"

###############################
#                             #
#            VPN              #
#                             #
###############################
# Anti VPN in all its glory
vpn:
  # Status of this anti-cheat: enabled or disabled
  isEnable: true
  # Text that will be displayed to the player when receiving a punishment
  punishText: "Suspicious use of VPN"
  # Choice of punishment for certain types of cheats
  #  0 - nothing,
  #  1 - only logging,
  #  2 - kick from the server + logging,
  #  3 - blocking by IP/SteamID + logging).
  punishType: 2
  # API key from the 'iphub.info' service
  API: "..."

###############################
#                             #
#          VEHICLE            #
#                             #
###############################
# Anti-cheat that prevents the use of Vehicle Cheat
vehicleCommands:
  # Status of this anti-cheat: enabled or disabled
  isEnable: true
  # Text that will be displayed to the player when receiving a punishment
  punishText: "Suspicious use of Vehicle Cheat Commands"
  # Choice of punishment for certain types of cheats
  #  0 - nothing,
  #  1 - only logging,
  #  2 - kick from the server + logging,
  #  3 - blocking by IP/SteamID + logging).
  punishType: 3

###############################
#                             #
#        Thunder              #
#                             #
###############################
# Anti-cheat that prevents the use of Thunder
thunder:
  # Status of this anti-cheat: enabled or disabled
  isEnable: true
  # Text that will be displayed to the player when receiving a punishment
  punishText: "Suspicion of creating a thunderstorm (cheats)"
  #  0 - nothing,
  #  1 - only logging,
  #  2 - kick from the server + logging,
  #  3 - blocking by IP/SteamID + logging).
  punishType: 2

###############################
#                             #
#        Fire                 #
#                             #
###############################
# Anti-cheat that prevents the use of Fire
fire:
  # Status of this anti-cheat: enabled or disabled
  isEnable: true
  # Text that will be displayed to the player when receiving a punishment
  punishText: "Suspicion of creating a fire (cheats)"
  #  0 - nothing,
  #  1 - only logging,
  #  2 - kick from the server + logging,
  #  3 - blocking by IP/SteamID + logging).
  punishType: 2

###############################
#                             #
#        EXTRA INFO           #
#                             #
###############################
# Anti-cheat that prevents the use of Extra Info
extraInfo:
  # Status of this anti-cheat: enabled or disabled
  isEnable: true
  # Text that will be displayed to the player when receiving a punishment
  punishText: "Suspicious use of Extra Info"
  # Choice of punishment for certain types of cheats
  #  0 - nothing,
  #  1 - only logging,
  #  2 - kick from the server + logging,
  #  3 - blocking by IP/SteamID + logging).
  punishType: 3

###############################
#                             #
#        Explosive            #
#                             #
###############################
# Anti-cheat that prevents the use of Explosive
explosive:
  # Status of this anti-cheat: enabled or disabled
  isEnable: true
  # Text that will be displayed to the player when receiving a punishment
  punishText: "Suspicion of bomb spawning"
  #  0 - nothing,
  #  1 - only logging,
  #  2 - kick from the server + logging,
  #  3 - blocking by IP/SteamID + logging).
  punishType: 2

###############################
#                             #
#        ChangeStats          #
#                             #
###############################
# Anti-cheat that prevents the use of Change Stats
changeStats:
  # Status of this anti-cheat: enabled or disabled
  isEnable: true
  # Text that will be displayed to the player when receiving a punishment
  punishText: "Suspicion of changing the player's stats through a cheat"
  #  0 - nothing,
  #  1 - only logging,
  #  2 - kick from the server + logging,
  #  3 - blocking by IP/SteamID + logging).
  punishType: 3

###############################
#                             #
#        ItemSpawner          #
#                             #
###############################
# Anti-cheat that prevents the use of Item Dupe
itemSpawner:
  # Status of this anti-cheat: enabled or disabled
  isEnable: true
  # Text that will be displayed to the player when receiving a punishment
  punishText: "Suspicion of item spawning"
  #  0 - nothing,
  #  1 - only logging,
  #  2 - kick from the server + logging,
  #  3 - blocking by IP/SteamID + logging).
  punishType: 3

###############################
#                             #
#            Skill            #
#                             #
###############################
# Anti-cheat that prevents the use of Skills Cheat
skill:
  # Status of this anti-cheat: enabled or disabled
  isEnable: true
  # Text that will be displayed to the player when receiving a punishment
  punishText: "Suspicious use of Skills Cheat"
  # Choice of punishment for certain types of cheats
  #  0 - nothing,
  #  1 - only logging,
  #  2 - kick from the server + logging,
  #  3 - blocking by IP/SteamID + logging).
  punishType: 3
  # The maximum level that can be obtained in a specified time
  maxLevel: 10
  # Minimum time (in-game) after which a player can level up above the specified level
  minHours: 2

###############################
#                             #
#        BrushTool            #
#                             #
###############################
# Anti-cheat that prevents the use of BrushTool
brushTool:
  # Status of this anti-cheat: enabled or disabled
  isEnable: true
  # Text that will be displayed to the player when receiving a punishment
  punishText: "Suspicious use of BrushTool"
  # Choice of punishment for certain types of cheats
  #  0 - nothing,
  #  1 - only logging,
  #  2 - kick from the server + logging,
  #  3 - blocking by IP/SteamID + logging).
  punishType: 2
  # An area where the player cannot place objects
  placeDistanceMin: 6
  placeDistanceMax: 15
  # Object placement time in ms, which is considered cheating
  placeTimeMin: 150
  placeTimeMax: 1500
  # Blacklist of sprites of objects to be placed on the map (for example, a water sprite cannot be placed in an honest way)
  # The name of the sprite is indicated, not the object itself
  blackListSprite:
    # Below is a list of water tiles
    - "blends_natural_02_0"
    - "blends_natural_02_1"
    - "blends_natural_02_2"
    - "blends_natural_02_3"
    - "blends_natural_02_4"
    - "blends_natural_02_5"
    - "blends_natural_02_6"
    - "blends_natural_02_7"
    - "blends_natural_02_8"
    - "blends_natural_02_9"
    - "blends_natural_02_10"
    - "blends_natural_02_11"
    - "blends_natural_02_12"
    - "blends_natural_02_13"
    - "blends_natural_02_14"
    - "blends_natural_02_15"
  # List of sprites for which anti-cheat will not work, you can specify a partial name
  whiteListSprite:
    - "invisible"
    - "roofs"

###############################
#                             #
#        ChatImpersonator     #
#                             #
###############################
# Filtering chat messages from players
chatImpersonator:
  # Status of this anti-cheat: enabled or disabled
  isEnable: true
  # Text that will be displayed to the player when receiving a punishment
  punishText: "Suspicion of sending a message on someone else's behalf"
  #  0 - nothing,
  #  1 - only logging,
  #  2 - kick from the server + logging,
  #  3 - blocking by IP/SteamID + logging).
  punishType: 3

###############################
#                             #
#        ChatFilter           #
#                             #
###############################
# Filtering chat messages from players
chatFilter:
  # Status of this chat filter: enabled or disabled
  isEnable: true
  # Text displayed when a message is blocked
  # Template: <WORD> - forbidden word
  # <SPACE> - space symbol
  blockingChatMessage: "<RGB:1,1,1> [ <SPACE> <RGB:0.8,0.4,0.2> ! <SPACE> <RGB:1,1,1> ] Your message has been blocked! Word: <SPACE> <RGB:0.8,0.4,0.2> <WORD>"
  # Text that will be displayed to the player when receiving a punishment
  # Template: <WORD> - forbidden word
  punishText: "Using prohibited words in chat"
  # Choice of punishment for certain types of cheats
  #  0 - nothing,
  #  1 - only logging + blocking message,
  #  2 - kick from the server + logging + blocking message,
  #  3 - blocking by IP/SteamID + logging) + blocking message.
  punishType: 1
  # List of words allowed on the server, even if they fall into prohibited patterns. List separated by commas.
  # Write in lower case.
  whiteListWords: "перебанит, потреблять"
  # List of individual words prohibited on the server. List separated by commas.
  # Write in lower case.
  blackListWords: "ахуенный, ахуеный, бля, блять, гавно, гей, долбоеб, долбоёб, еба, ебля, ебу, жопа, клитор, 
  манда, москаль, нехуя, нихуя, оргазм, оргия, офигел, охрененный охеренный, охуенный, охуеный, пздц, пипец, ппц, 
  прошмандовка, ска, сперма, сук, сука, сучка, уебан, фига, хер, хера, херня, херота, хрен, хуй, хуйня, хуйца, хули, 
  хуя, шалава, шлюха, тварь, хохол, чурка"
  # Link to file with swear words
  banWordsRawListUrl:
    - "https://raw.githubusercontent.com/bars38/Russian_ban_words/master/words.txt"
    - "https://raw.githubusercontent.com/Brov3r/Protegon/main/BanWords/filter_steam_russian.txt"
  # Regular expression patterns for banned words
  # Write in lower case.
  patternListWords:
    - "\\w*секс\\w*"
    - "\\w*[@#]\\w+" # Tag Discord spam
    - "\\w*https?://\\w*" # Link spam
    - "\\w*пид(р|ар|ор)\\w*"
    - "\\w*(го(вн|мик|мек)|(а|о)ху(е|ё|и|й))\\w*"
    - "\\w*((е|ё)ба(н|л|ш|т)|бля(д|т)|(е|ё)б(у|ись|ну(т|л|ш|в)|ка|ли|ен|ищ|ит|ош))\\w*"
    - "\\w*(мудак|г(о|а)ндон|пизд|залуп|х(у(й|е|ё|и|я|ю)|ер|рен))\\w*"
    - "n+([ehiy]+|ay|ey|io|[il]+)[bgq$]+h?(a+|aer|a+h+|a+r+|e+|ea|eoa|e+r+|ie|ier|let|lit|o|or|r+|u|uh|uhr|u+r+|ward|y+)s*"
    - "f[ae]y?g+[oeiu]+t+s?"

###############################
#                             #
#        SafeHouse            #
#                             #
###############################
# Anti-cheat that prevents the use of SafeHouse Cheat
safeHouse:
  # Status of this anti-cheat: enabled or disabled
  isEnable: true
  # Text that will be displayed to the player when receiving a punishment
  punishText: "Suspicion of using a cheat on safehouse"
  #  0 - nothing,
  #  1 - only logging,
  #  2 - kick from the server + logging,
  #  3 - blocking by IP/SteamID + logging).
  punishType: 3

###############################
#                             #
#        SafeHouse Items      #
#                             #
###############################
# Anti-cheat that prevents the use of SafeHouse Cheat
safeHouseItems:
  # Status of this anti-cheat: enabled or disabled
  isEnable: true
  # Text that will be displayed to the player when receiving a punishment
  punishText: "Suspicion of attempting to steal items from someone else's safehouse"
  #  0 - nothing,
  #  1 - only logging,
  #  2 - kick from the server + logging,
  #  3 - blocking by IP/SteamID + logging).
  punishType: 2